"""
Django settings for project project.

Generated by 'django-admin startproject' using Django 3.1.7.

For more information on this file, see
https://docs.djangoproject.com/en/3.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.1/ref/settings/
"""

from pathlib import Path
import datetime


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
#SECRET_KEY = os.getenv("SECRET_KEY")
SECRET_KEY = 'or!473&bx2l4lc5vx^k=3#2@kh@jrv5g485btq5i+m9otzk0w8'
# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ["bugbounty.pythonanywhere.com"]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'phonenumber_field',
    'rest_framework',
    'djoser',
    'taggit',
    'taggit_serializer',
    #'ckeditor',
    #'ckeditor_uploader',
    'corsheaders',
   # "drf_recaptcha",
    'storages',
    "users",
    "admins",
    "employees",
    'hackers',
    'programs',
    'rest_framework_simplejwt.token_blacklist',

    'drf_yasg',
    "django_filters",


]

# import locale
# def getpreferredencoding(do_setlocale = True):
#     return "utf-8"
# locale.getpreferredencoding = getpreferredencoding

import _locale
_locale._getdefaultlocale = (lambda *args: ['en_US', 'utf8'])

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.locale.LocaleMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'project.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'project.wsgi.application'


AUTH_USER_MODEL = 'users.User'

AUTHENTICATION_BACKENDS = [
 'django.contrib.auth.backends.ModelBackend',
 'users.custom_auth.EmailAuthBackend',
]

# Database
# https://docs.djangoproject.com/en/3.1/ref/settings/#databases

#DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.sqlite3',
#         'NAME': BASE_DIR / 'db.sqlite3',
#     }
#}

DATABASES = {
    'default': {
         'ENGINE': 'django.db.backends.mysql',
         'NAME': 'bugbounty$default',
         'USER': 'bugbounty',
         'PASSWORD': 'robot9000',
         'HOST': 'bugbounty.mysql.pythonanywhere-services.com',   # Or an IP Address that your DB is hosted on
         #'PORT': '3306',
     }
 }



CORS_ALLOW_ALL_ORIGINS = True


# Password validation
# https://docs.djangoproject.com/en/3.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

REST_FRAMEWORK = {

    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
    "DEFAULT_SCHEMA_CLASS": "rest_framework.schemas.openapi.AutoSchema",

    #'DEFAULT_THROTTLE_CLASSES': [
      #  'rest_framework.throttling.AnonRateThrottle',
       # 'rest_framework.throttling.UserRateThrottle'
   # ],
    'DEFAULT_THROTTLE_RATES': {
        'anon': '1/day',
        'user': '1/minute'
    }
}

DJOSER = {
    'LOGIN_FIELD':'email',
    'PASSWORD_RESET_CONFIRM_URL': 'https://development-verison.herokuapp.com/reset-password?uid={uid}&token={token}',
    'USERNAME_RESET_CONFIRM_URL': 'https://development-verison.herokuapp.com/verify-email/?uid={uid}&token={token}',
    'ACTIVATION_URL': '#/activate/{uid}/{token}',
    'SEND_ACTIVATION_EMAIL': True,
    'PASSWORD_CHANGED_EMAIL_CONFIRMATION': True,
    'USERNAME_CHANGED_EMAIL_CONFIRMATION': True,
    "USERNAME_RESET_SHOW_EMAIL_NOT_FOUND": True
    #'SERIALIZERS': {},
}


SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': datetime.timedelta(minutes=20),
    'REFRESH_TOKEN_LIFETIME': datetime.timedelta(days=1),
    'ROTATE_REFRESH_TOKENS': True,
    'BLACKLIST_AFTER_ROTATION': True,
    'UPDATE_LAST_LOGIN': False,
    'ALGORITHM': 'HS256',
}
# Internationalization
# https://docs.djangoproject.com/en/3.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.1/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / "static"


#STATICFILES_DIRS = [
#    BASE_DIR / "static",
#    '/var/www/static/',
# ]

STATIC_ROOT = "/var/www/example.com/static/"
MEDIA_URL = '/media/'

MEDIA_ROOT = BASE_DIR/"media"

STATIC_ROOT = BASE_DIR / "static"


# STATICFILES_DIRS = [
#     BASE_DIR / "static",
#     '/var/www/static/',
# ]


MEDIA_URL = '/media/'

MEDIA_ROOT = BASE_DIR/"media"

#Mail configuration
EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_HOST_USER = 'ah.khaled2020@gmail.com'
EMAIL_HOST_PASSWORD = 'flgxozfsuexnljrj'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
DEFAULT_FROM_EMAIL = 'ah.khaled2020@gmail.com'

# Twilio API credentials
# (find here https://www.twilio.com/console)
TWILIO_ACCOUNT_SID="AC4cc10d126e83850b1cb5a3ad9c6e2194"
TWILIO_AUTH_TOKEN="75be0517d1a247262280da584c72a68d"

# Verification Service SID
# (create one here https://www.twilio.com/console/verify/services)
VERIFICATION_SID="VA5b18bed7b92ffda2cd090e88b6dadb16"



# import _locale
# _locale._getdefaultlocale = (lambda *args: ['en_US', 'utf8'])