# Generated by Django 3.1.7 on 2021-09-17 00:05

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hackers', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='timeline',
            options={'verbose_name': 'TimeLine', 'verbose_name_plural': 'TimeLines'},
        ),
        migrations.AlterField(
            model_name='report',
            name='contributors',
            field=models.ManyToManyField(related_name='reports_work', to=settings.AUTH_USER_MODEL),
        ),
    ]
