# Generated by Django 3.1.7 on 2021-09-19 19:45

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('hackers', '0002_auto_20210917_0205'),
    ]

    operations = [
        migrations.AddField(
            model_name='bounty',
            name='transaction_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
