# Generated by Django 3.1.7 on 2021-09-19 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hackers', '0003_bounty_transaction_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='bounty',
            name='state',
            field=models.CharField(choices=[('accepted', 'Accepted'), ('rejected', 'Rejected'), ('processing', 'Processing'), ('on_hold', 'on hold')], default='processing', max_length=50),
        ),
    ]
