# Generated by Django 3.1.7 on 2021-09-22 21:00

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hackers', '0005_weakness_cwe_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='contributors',
            field=models.ManyToManyField(blank=True, related_name='reports_work', to=settings.AUTH_USER_MODEL),
        ),
    ]
